# Generated by Django 4.0.2 on 2022-03-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_review', models.FloatField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('manufacturer', models.CharField(max_length=50)),
                ('deliveryIn', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('ECS', 'Electronics'), ('SUP', 'Supplements'), ('NUT', 'Nutrition'), ('BKS', 'Books')], max_length=3)),
                ('ageRestriction', models.CharField(blank=True, choices=[('0', 'FSK 0'), ('6', 'FSK 6'), ('12', 'FSK 12'), ('16', 'FSK 16'), ('18', 'FSK 18')], default=None, max_length=2, null=True)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('extended_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extended_users', related_query_name='extended_user', to='Useradmin.extendeduser')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article_review', models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], default='', max_length=1)),
                ('report', models.BooleanField(default=False)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Article.article')),
                ('extended_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Useradmin.extendeduser')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_or_down', models.CharField(choices=[('U', 'up'), ('D', 'down')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Article.comment')),
                ('extended_user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Useradmin.extendeduser')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_contact', models.CharField(default='', max_length=100)),
                ('extended_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Useradmin.extendeduser')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Article.article')),
                ('weight', models.CharField(default='100g', max_length=20)),
                ('field_of_use', models.CharField(choices=[('RLX', 'Relaxation & Sleep'), ('VIT', 'Vitamins'), ('EGY', 'Energy'), ('STR', 'Strength')], max_length=3)),
                ('recommended_frequency_of_use', models.CharField(default='One daily unit', max_length=20)),
                ('ingredients', models.CharField(default='No Ingredients given', max_length=300)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='article-images/supplements')),
                ('related_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_supplement', to='Article.article')),
            ],
            bases=('Article.article',),
        ),
        migrations.CreateModel(
            name='Superfood',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Article.article')),
                ('weight', models.CharField(default='100g', max_length=20)),
                ('nutritional_values', models.CharField(blank=True, default='No Nutritional Values given', max_length=500)),
                ('vegan', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='article-images/superfoods')),
                ('related_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_superfood', to='Article.article')),
            ],
            bases=('Article.article',),
        ),
        migrations.CreateModel(
            name='ElectronicDevice',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Article.article')),
                ('type', models.CharField(choices=[('SFW', 'Software'), ('HAW', 'Hardware'), ('FIT', 'Fitness Tracker'), ('SLT', 'Sleep Tracker')], max_length=3)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('battery_life', models.CharField(default='3 hours', max_length=30)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='article-images/electronic-devices')),
                ('related_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_e_device', to='Article.article')),
            ],
            bases=('Article.article',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Article.article')),
                ('author', models.CharField(max_length=60)),
                ('pages', models.IntegerField(default=100)),
                ('isbn', models.IntegerField(unique=True)),
                ('genre', models.CharField(choices=[('PRO', 'Productivity'), ('PER', 'Personality Development'), ('HAP', 'Happiness'), ('HLT', 'Health')], default='No Genre specified.', max_length=3)),
                ('type', models.CharField(choices=[('HAR', 'Hardcover'), ('PAP', 'Paperback'), ('EBK', 'E-Book')], default='Book', max_length=3)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='article-images/books')),
                ('related_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_book', to='Article.article')),
            ],
            bases=('Article.article',),
        ),
    ]
