# Generated by Django 4.0.2 on 2022-03-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='extended_user',
        ),
    ]
