# Generated by Django 4.0.2 on 2022-03-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
        ('Article', '0002_remove_vote_extended_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='extended_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Useradmin.extendeduser'),
        ),
    ]
