# Generated by Django 4.0 on 2022-03-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_vote_extended_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superfood',
            old_name='nutritional_values',
            new_name='ingredients',
        ),
    ]
