# Generated by Django 4.0.2 on 2022-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_rename_nutritional_values_superfood_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfood',
            name='ingredients',
            field=models.CharField(blank=True, default='No Ingredients given', max_length=500),
        ),
    ]
